version: '3.5'
services:
  sut:
    container_name: "aws-cli_sut"
    build:
      context: docker/python
      dockerfile: Dockerfile
    entrypoint: ["/var/run_tests.sh"]
    command: ["/var/run_tests.sh"]
