version: '3.5'
services: 
    aws:
        container_name: aws-cli_command
        build: 
            context: docker/python
            dockerfile: Dockerfile
        environment:
            - AWS_ACCESS_KEY_ID=$AWS_KEY
            - AWS_SECRET_ACCESS_KEY=$AWS_SECRET
        volumes: 
            - ./project:/var/project
        working_dir: /var/project
        entrypoint: ['/usr/local/bin/aws']