version: '3.5'
services:
  aws:
    container_name: aws-cli_command
    image: tommynovember7/aws-cli:latest
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    volumes:
      - ./project:/aws

  sut:
    container_name: aws-cli_sut
    build:
      context: docker/python
      dockerfile: Dockerfile
    entrypoint: ['/var/run_tests.sh']
    command: ['/var/run_tests.sh']

  hadolint:
    container_name: aws-cli_hadolint
    image: hadolint/hadolint:latest-debian
    volumes:
      - ./:/var/project
    working_dir: /var/project
    entrypoint: ['/bin/hadolint', '--config', './docker/hadolint.yaml']
