name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_KEY: ${{ secrets.AWS_KEY }}
      AWS_SECRET: ${{ secrets.AWS_SECRET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - uses: actions/checkout@v1

      - name: Build the container
        run: |
          docker login docker.pkg.github.com -u tommyheavenly7 --password ${{ PACKAGE_TOKEN }}
          docker-compose up --no-start --force-recreate --build
          docker-compose ps

      - name: Run tests
        run: docker-compose run --rm sut
