name: "BUILD IAMGES"

on:
  create:
    tags:
      - "*"
jobs:
  run_tests:
    runs-on: ubuntu-latest

    env:
      AWS_KEY: ${{ secrets.AWS_KEY }}
      AWS_SECRET: ${{ secrets.AWS_SECRET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - uses: actions/checkout@v2

      - name: Build the container
        run: |
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          echo ${{ secrets.PACKAGE_TOKEN }} | docker login ghcr.io -u tommyheavenly7 --password-stdin
          docker-compose up --no-start --force-recreate --build
          docker-compose ps

      - name: Run tests
        run: docker-compose run --rm sut
