name: "BUILD IAMGES"

on:
  create:
    tags:
      - "*"
jobs:
  run_tests:
    runs-on: ubuntu-latest

    env:
      AWS_KEY: ${{ secrets.AWS_KEY }}
      AWS_SECRET: ${{ secrets.AWS_SECRET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - uses: actions/checkout@v2

      - name: Build the container
        run: |
          docker login docker.pkg.github.com -u ${{ secrets.USER_NAME }} --password ${{ secrets.PACKAGE_TOKEN }}
          docker-compose up --no-start --force-recreate --build
          docker-compose ps

      - name: Run tests
        run: docker-compose run --rm sut

  build_images:
    needs: run_tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build a new container
        run: |
          echo ${{ secrets.PACKAGE_TOKEN }} | docker login docker.pkg.github.com -u tommyheavenly7 --password-stdin
          echo ${{ steps.vars.outputs.tag }}
          docker build --pull --tag docker.pkg.github.com/tommyheavenly7/aws-cli/aws:${{ steps.vars.outputs.tag }} ./docker/python/
          docker push docker.pkg.github.com/tommyheavenly7/aws-cli/aws:${{ steps.vars.outputs.tag }}
          docker build --pull --tag docker.pkg.github.com/tommyheavenly7/aws-cli/aws:latest ./docker/python/
          docker push docker.pkg.github.com/tommyheavenly7/aws-cli/aws:latest
          docker build --pull --tag docker.pkg.github.com/tommyheavenly7/aws-cli/aws-1x:${{ steps.vars.outputs.tag }} ./docker/python/
          docker push docker.pkg.github.com/tommyheavenly7/aws-cli/aws-1x:${{ steps.vars.outputs.tag }}
          docker build --pull --tag docker.pkg.github.com/tommyheavenly7/aws-cli/aws-1x:latest ./docker/python/
          docker push docker.pkg.github.com/tommyheavenly7/aws-cli/aws-1x:latest
