name: "BUILD IAMGES"

on:
  push:
    tags:
      - "[0-9].[0-9].[0-9]"

jobs:
  run_tests:
    runs-on: ubuntu-latest

    env:
      AWS_KEY: ${{ secrets.AWS_KEY }}
      AWS_SECRET: ${{ secrets.AWS_SECRET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - uses: actions/checkout@v2

      - name: Build the container
        run: |
          docker login docker.pkg.github.com -u ${{ secrets.USER_NAME }} --password ${{ secrets.PACKAGE_TOKEN }}
          docker-compose up --no-start --force-recreate --build
          docker-compose ps

      - name: Run tests
        run: docker-compose run --rm sut

  build_images:
    needs: run_tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Build a new container
        run: |
          echo ${{ secrets.PACKAGE_TOKEN }} | docker login docker.pkg.github.com -u ${{ secrets.USER_NAME }} --password-stdin
          echo ${{ steps.get_version.outputs.VERSION }}
          docker build --tag docker.pkg.github.com/tommyheavenly7/aws-cli/aws:${{ steps.get_version.outputs.VERSION }} ./docker/python/
          docker push docker.pkg.github.com/tommyheavenly7/aws-cli/aws:${{ steps.get_version.outputs.VERSION }}
